# NumPy Basics





In [1]:
# import library numpy
import numpy

# import library numpy dengan menggunakan alias np
import numpy as np

In [9]:
# pembuatan array  menggunakan NumPy
arr = np.array([1, 2, 3, 4, 5])

print(arr)

# menampilkan jenis tipe dari array
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
# pembuatan array  menggunakan NumPy berbasis Tuple
arr = np.array((1, 2, 3, 4, 5))

print(arr)

# menampilkan jenis tipe dari array
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensi Array


In [4]:
# array 1D
arr1d = np.array([1, 2, 3, 4, 5])
# array 2D
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
# array 3D
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
# dimensi yang lebih tinggi
arr5d = np.array([1, 2, 3, 4], ndmin=5)

# menampilkan dimensi dari array
print("Dimensi: ", arr1d.ndim)
print("Dimensi: ", arr2d.ndim)
print("Dimensi: ", arr3d.ndim)
print("Dimensi: ", arr5d.ndim)

Dimensi:  1
Dimensi:  2
Dimensi:  3
Dimensi:  5


## Accessing Array

In [5]:
# mengakses dengan menggunakan index
arr = np.array([1, 2, 3, 4])
print(arr[0])

# mengakses array 2D dengan menggunakan index
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

# menggunakan index negatif
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

1
2nd element on 1st row:  2
Last element from 2nd dim:  10


## Reshaping & Resizing Array
Digunakan untuk memodifikasi ukuran dan dimensi dari NumPy array

In [7]:
import numpy as np

# Membuat array 1-dimensi
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Melakukan reshape pada array menjadi ukuran 2-dimensi dengan 2 rows and 3 columns
array_2d = array_1d.reshape(2, 3)

print("Original array:")
print(array_1d)

print("Reshaped array:")
print(array_2d)

# Resize array menjadi array yang memiliki jumlah elemen berbeda
resized_array = np.resize(array_1d, (3, 4))

print("Resized array:")
print(resized_array)


Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]
Resized array:
[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


## Concatenating & Splitting Array
Operasi ini berguna ketika bekerja dengan banyak array

In [8]:
# Membuat 2 buah array 1D
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concate atau menggabungkan kedua array secara horizontal
concatenated_array = np.concatenate((array1, array2), axis=0)

print("Concatenated array:")
print(concatenated_array)

# Split array menjadi bentuk awal
split_arrays = np.split(concatenated_array, 2)

print("Split arrays:")
print(split_arrays)

Concatenated array:
[1 2 3 4 5 6]
Split arrays:
[array([1, 2, 3]), array([4, 5, 6])]


##Transposing & Swapping Array
Digunakan untuk memanipulasi dimensi dan orientasi dari sebuah array di dalam NumPy

In [8]:
# Membuat array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Original array:")
print(array_2d)

# Transpose array
transposed_array = np.transpose(array_2d)

print("Transposed array:")
print(transposed_array)

# Swap atau menukar index dari array
swapped_array = np.swapaxes(array_2d, 0, 1)

print("Swapped array:")
print(swapped_array)


Original array:
[[1 2 3]
 [4 5 6]]
Transposed array:
[[1 4]
 [2 5]
 [3 6]]
Swapped array:
[[1 4]
 [2 5]
 [3 6]]
