# Arrays and Array Operations in NumPy

## Array Indexing and Slicing in NumPy

Indexing: dilakukan untuk mengakses elemen di dalam array berdasarkan index dari elemen yang dituju

Slicing: dilakukan untuk megakses atau memilih subset array di dalam suatu array

## Indexing and slicing one-dimensional arrays

In [1]:
import numpy as np

# membuat array 1D dengan numpy
numbers = np.array([1, 2, 3, 4, 5])

# membuat variable baru yang berisi array dengan index 1
second_element = numbers[1]

# contoh slicing
# sintaks umum: array[start:stop:step]
slicing = numbers[1:4:2]

print(second_element)
print(slicing)

2
[2 4]


## Indexing and slicing multi-dimensional arrays

In [2]:
# Membuat array 2D dengan numpy
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# mengakses elemen spesifik di dalam array
element_1_2 = matrix[1, 2]
first_row = matrix[0, :]
last_column = matrix[:, 2]

print(element_1_2)
print(first_row)
print(last_column)

6
[1 2 3]
[3 6 9]


## Boolean indexing and fancy indexing

In [4]:
numbers = np.array([1, 2, 3, 4, 5])

# Boolean indexing
is_even = numbers % 2 == 0
even_numbers = numbers[is_even]

print(even_numbers)

[2 4]


In [5]:
# Fancy indexing
indices = [0, 2, 4]
selected_numbers = numbers[indices]

print(selected_numbers)

[1 3 5]


## Mathematical Operations with NumPy Arrays

## Element-wise operations

In [6]:
import numpy as np

# membuat dua buah numpy array
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# menjumlahkan langsung kedua array tersebut
result = arr1 + arr2
print(result)

[ 6  8 10 12]


## Mathematical functions

In [7]:
numbers = np.array([2, 4, 6, 8, 10])

sum_result = np.sum(numbers)
mean_result = np.mean(numbers)
max_result = np.max(numbers)

print("Sum:", sum_result)
print("Mean:", mean_result)
print("Maximum:", max_result)

Sum: 30
Mean: 6.0
Maximum: 10


## Broadcasting in NumPy

Memiliki tiga aturan dalam broadcasting di dalam NumPy
1. Jika array memiliki jumlah dimensi yang berbeda, array dengan jumlah dimensi yang lebih sedikit akan ditambahkan padding di sebelah kiri hingga dimensinya cocok.
2. Jika array memiliki ukuran yang berbeda pada dimensi tertentu, array dengan ukuran 1 pada dimensi tersebut akan diperluas agar bisa cocok dengan ukuran array lainnya.

In [8]:
# melakukan operasi pada numpy array yang memiliki dimensi/shape berbeda
arr = np.array([[1], [2], [3]])
scalar = 2

result = arr * scalar
print(result)

[[2]
 [4]
 [6]]


In [9]:
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([10, 20, 30, 40])

result = arr1 * arr2
print(result)

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]]
